name: Python Lint

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:

jobs:
  quality:
    name: isort → black → flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          
      - name: pip install
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install isort black flake8

      - name: .env 파일 생성
        run: |
          echo "TUKOREA_ID=${{ secrets.TUKOREA_ID }}"   >> .env
          echo "TUKOREA_PW=${{ secrets.TUKOREA_PW }}"   >> .env
          echo "ENVIRONMENT=${{ secrets.ENVIRONMENT }}" >> .env
          echo "CRAWLER_LOG_LEVEL=${{ secrets.CRAWLER_LOG_LEVEL }}" >> .env
          echo "CRAWLER_LOG_FILE=${{ secrets.CRAWLER_LOG_FILE }}"   >> .env

      - name: 자동 포맷 및 import 정렬
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "▶ isort 및 Black 자동 적용"
          isort .
          black .
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: apply isort & black fixes" || echo "변경사항 없음"

      - name: isort 검사
        run: |
          echo "▶ isort import 정렬 검사"
          isort --check-only .

      - name: Black 검사
        run: |
          echo "▶ Black 포맷 검사"
          black --check .

      - name: Flake8 검사
        run: |
          echo "▶ Flake8 린팅 (.flake8 설정 사용)"
          flake8 --config .flake8 .
